# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6a5e47010d5afdc39b18dc5478719fe0881fb9dce41501556b1136f42f77d2bc0c9cd1d4acb1116bc31f46c75de86c305ab56754df9ee543aa1e85306addf839

test:
  secret_key_base: 0b39817f44b718f3ecec45bd87c8c4c8a3625827f82d63193d88fcf336346c399ad1c29a2d0cf864b43bc19568b242f94b63fa35a34ba34ac2acfec317fb635e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
